version: "3.8"

services:
  postgres-db:
    container_name: mukbang_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: yin
      POSTGRES_PASSWORD: yang
      POSTGRES_DB: mukbang_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5424:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: local-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  postgresql_data:
    driver: local
  minio-data:
