CREATE TABLE post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(255),
    users_id      BIGINT                                  NOT NULL,
    created_on    TIMESTAMP WITHOUT TIME ZONE,
    restaurant_id BIGINT,
    post_id       BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE restaurant
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    username VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_created_posts
(
    users_id         BIGINT NOT NULL,
    created_posts_id BIGINT NOT NULL
);

ALTER TABLE users_created_posts
    ADD CONSTRAINT uc_users_created_posts_createdposts UNIQUE (created_posts_id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_POST FOREIGN KEY (post_id) REFERENCES restaurant (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USERS FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE users_created_posts
    ADD CONSTRAINT fk_usecrepos_on_post FOREIGN KEY (created_posts_id) REFERENCES post (id);

ALTER TABLE users_created_posts
    ADD CONSTRAINT fk_usecrepos_on_users FOREIGN KEY (users_id) REFERENCES users (id);