CREATE TABLE happy_hour_deal
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NULL,
    deal_type VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    value INTEGER,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    CONSTRAINT pk_happyhourdeal PRIMARY KEY (id),
    CONSTRAINT fk_happyhourdeal_restaurant
        FOREIGN KEY (restaurant_id)
            REFERENCES restaurant(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_happy_hour_time
    ON happy_hour_deal(day_of_week, start_time, end_time);