CREATE TABLE day_of_week_entity
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day VARCHAR(255),
    CONSTRAINT pk_dayofweekentity PRIMARY KEY (id)
);

CREATE TABLE day_of_week_entity_happy_hours
(
    day_of_week_entity_id BIGINT NOT NULL,
    happy_hours_id        BIGINT NOT NULL
);

CREATE TABLE happy_hour_deal_happy_hours
(
    happy_hour_deal_id BIGINT NOT NULL,
    happy_hours_id     BIGINT NOT NULL
);

CREATE TABLE happy_hour_entity
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_happyhourentity PRIMARY KEY (id)
);

CREATE TABLE happy_hour_entity_days_of_the_week
(
    happy_hour_entity_id BIGINT NOT NULL,
    days_of_the_week_id  BIGINT NOT NULL
);

CREATE TABLE happy_hour_entity_deals
(
    happy_hour_entity_id BIGINT NOT NULL,
    deals_id             BIGINT NOT NULL
);

ALTER TABLE day_of_week_entity_happy_hours
    ADD CONSTRAINT fk_dayofweeenthaphou_on_day_of_week_entity FOREIGN KEY (day_of_week_entity_id) REFERENCES day_of_week_entity (id);

ALTER TABLE day_of_week_entity_happy_hours
    ADD CONSTRAINT fk_dayofweeenthaphou_on_happy_hour_entity FOREIGN KEY (happy_hours_id) REFERENCES happy_hour_entity (id);

ALTER TABLE happy_hour_deal_happy_hours
    ADD CONSTRAINT fk_haphoudeahaphou_on_happy_hour_deal FOREIGN KEY (happy_hour_deal_id) REFERENCES happy_hour_deal (id);

ALTER TABLE happy_hour_deal_happy_hours
    ADD CONSTRAINT fk_haphoudeahaphou_on_happy_hour_entity FOREIGN KEY (happy_hours_id) REFERENCES happy_hour_entity (id);

ALTER TABLE happy_hour_entity_days_of_the_week
    ADD CONSTRAINT fk_haphouentdayofthewee_on_day_of_week_entity FOREIGN KEY (days_of_the_week_id) REFERENCES day_of_week_entity (id);

ALTER TABLE happy_hour_entity_days_of_the_week
    ADD CONSTRAINT fk_haphouentdayofthewee_on_happy_hour_entity FOREIGN KEY (happy_hour_entity_id) REFERENCES happy_hour_entity (id);

ALTER TABLE happy_hour_entity_deals
    ADD CONSTRAINT fk_haphouentdea_on_happy_hour_deal FOREIGN KEY (deals_id) REFERENCES happy_hour_deal (id);

ALTER TABLE happy_hour_entity_deals
    ADD CONSTRAINT fk_haphouentdea_on_happy_hour_entity FOREIGN KEY (happy_hour_entity_id) REFERENCES happy_hour_entity (id);

ALTER TABLE restaurant
    ALTER COLUMN cuisine TYPE VARCHAR(255) USING (cuisine::VARCHAR(255));

ALTER TABLE happy_hour_deal
    ALTER COLUMN day_of_week TYPE VARCHAR(255) USING (day_of_week::VARCHAR(255));

ALTER TABLE happy_hour_deal
    ALTER COLUMN day_of_week DROP NOT NULL;

ALTER TABLE happy_hour_deal
    ALTER COLUMN deal_type TYPE VARCHAR(255) USING (deal_type::VARCHAR(255));

ALTER TABLE happy_hour_deal
    ALTER COLUMN deal_type DROP NOT NULL;

ALTER TABLE restaurant
    ALTER COLUMN email TYPE VARCHAR(255) USING (email::VARCHAR(255));

ALTER TABLE happy_hour_deal
    ALTER COLUMN end_time DROP NOT NULL;

ALTER TABLE restaurant
    ALTER COLUMN number TYPE VARCHAR(255) USING (number::VARCHAR(255));

ALTER TABLE happy_hour_deal
    ALTER COLUMN restaurant_id DROP NOT NULL;

ALTER TABLE happy_hour_deal
    ALTER COLUMN start_time DROP NOT NULL;

ALTER TABLE restaurant
    ALTER COLUMN website TYPE VARCHAR(255) USING (website::VARCHAR(255));